"""core tables

Revision ID: e482c64a233a
Revises: bc5099e1c752
Create Date: 2026-03-08 13:13:09.231765+00:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e482c64a233a'
down_revision = 'bc5099e1c752'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('setor_mercado', sa.String(length=255), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('email_responsavel', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sobrenome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tipo_aplicacao', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rodadas_aplicacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_encerramento', sa.Date(), nullable=True),
    sa.Column('criado_por', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criado_por'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rodadas_aplicacao_cliente_id'), 'rodadas_aplicacao', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_rodadas_aplicacao_criado_por'), 'rodadas_aplicacao', ['criado_por'], unique=False)
    op.create_table('setores_empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setores_empresa_cliente_id'), 'setores_empresa', ['cliente_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('rodada_id', sa.UUID(), nullable=False),
    sa.Column('setor_id', sa.UUID(), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('testdef_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas_aplicacao.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['setor_id'], ['setores_empresa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_cliente_id'), 'attempts', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_attempts_participant_id'), 'attempts', ['participant_id'], unique=False)
    op.create_index(op.f('ix_attempts_rodada_id'), 'attempts', ['rodada_id'], unique=False)
    op.create_index(op.f('ix_attempts_setor_id'), 'attempts', ['setor_id'], unique=False)
    op.create_index(op.f('ix_attempts_status'), 'attempts', ['status'], unique=False)
    op.create_index(op.f('ix_attempts_token_hash'), 'attempts', ['token_hash'], unique=True)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=1), nullable=False),
    sa.Column('letter_scored', sa.String(length=2), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_number', name='uq_answers_attempt_question')
    )
    op.create_index(op.f('ix_answers_attempt_id'), 'answers', ['attempt_id'], unique=False)
    op.create_table('computed_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top3', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top5', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bottom3', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interpretations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('premium_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computed_results_attempt_id'), 'computed_results', ['attempt_id'], unique=True)
    op.create_table('report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_attempt_id'), 'report_snapshots', ['attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_snapshots_attempt_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_computed_results_attempt_id'), table_name='computed_results')
    op.drop_table('computed_results')
    op.drop_index(op.f('ix_answers_attempt_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_attempts_token_hash'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_status'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_setor_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_rodada_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_participant_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_cliente_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_setores_empresa_cliente_id'), table_name='setores_empresa')
    op.drop_table('setores_empresa')
    op.drop_index(op.f('ix_rodadas_aplicacao_criado_por'), table_name='rodadas_aplicacao')
    op.drop_index(op.f('ix_rodadas_aplicacao_cliente_id'), table_name='rodadas_aplicacao')
    op.drop_table('rodadas_aplicacao')
    op.drop_table('participants')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
